services:
    haproxy:
        image: haproxy:latest
        container_name: haproxy
        ports:
            - '80:80'
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        depends_on:
            - syslog
            - server1
            - server2
        logging:
            driver: none

    syslog:
        image: balabit/syslog-ng:latest
        container_name: syslog
        volumes:
            - ./logs:/var/log
            - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
        ports:
            - '514:514/udp'

    server1:
        build:
            context: ./server1
        container_name: server1
        ports:
            - '8081:8081'

    server2:
        build:
            context: ./server2
        container_name: server2
        ports:
            - '8082:8082'
