version: '3.8'
services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - server1
      - server2

  server1:
    build:
      context: ./server1
    container_name: server1
    ports:
      - "8081:8081"

  server2:
    build:
      context: ./server2
    container_name: server2
    ports:
      - "8082:8082"
